# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1419, 883)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Input_Block = QtWidgets.QVBoxLayout()
        self.Input_Block.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Input_Block.setObjectName("Input_Block")
        self.Blcok1 = QtWidgets.QVBoxLayout()
        self.Blcok1.setObjectName("Blcok1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Block1_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Block1_label.setFont(font)
        self.Block1_label.setObjectName("Block1_label")
        self.horizontalLayout_2.addWidget(self.Block1_label)
        self.Block1_combo = QtWidgets.QComboBox(self.centralwidget)
        self.Block1_combo.setObjectName("Block1_combo")
        self.Block1_combo.addItem("")
        self.Block1_combo.addItem("")
        self.Block1_combo.addItem("")
        self.Block1_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.Block1_combo)
        self.Blcok1.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Image1_view = ImageView(self.centralwidget)
        self.Image1_view.setMinimumSize(QtCore.QSize(400, 0))
        self.Image1_view.setAutoFillBackground(True)
        self.Image1_view.setObjectName("Image1_view")
        self.horizontalLayout_3.addWidget(self.Image1_view)
        self.Image1_change = ImageView(self.centralwidget)
        self.Image1_change.setMinimumSize(QtCore.QSize(400, 0))
        self.Image1_change.setAutoFillBackground(True)
        self.Image1_change.setObjectName("Image1_change")
        self.horizontalLayout_3.addWidget(self.Image1_change)
        self.Blcok1.addLayout(self.horizontalLayout_3)
        self.Input_Block.addLayout(self.Blcok1)
        self.Block2 = QtWidgets.QVBoxLayout()
        self.Block2.setObjectName("Block2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Block2_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Block2_label.setFont(font)
        self.Block2_label.setObjectName("Block2_label")
        self.horizontalLayout_4.addWidget(self.Block2_label)
        self.Block2_combo = QtWidgets.QComboBox(self.centralwidget)
        self.Block2_combo.setObjectName("Block2_combo")
        self.Block2_combo.addItem("") 
        self.Block2_combo.addItem("")
        self.Block2_combo.addItem("")
        self.Block2_combo.addItem("")
        self.horizontalLayout_4.addWidget(self.Block2_combo)
        self.Block2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Image2_view = ImageView(self.centralwidget)
        self.Image2_view.setAutoFillBackground(True)
        self.Image2_view.setObjectName("Image2_view")
        self.horizontalLayout_5.addWidget(self.Image2_view)
        self.Image2_change = ImageView(self.centralwidget)
        self.Image2_change.setAutoFillBackground(True)
        self.Image2_change.setObjectName("Image2_change")
        self.horizontalLayout_5.addWidget(self.Image2_change)
        self.Block2.addLayout(self.horizontalLayout_5)
        self.Input_Block.addLayout(self.Block2)
        self.gridLayout_2.addLayout(self.Input_Block, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choose_output = QtWidgets.QHBoxLayout()
        self.choose_output.setObjectName("choose_output")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.choose_output.addWidget(self.label)
        self.combo_choose_output = QtWidgets.QComboBox(self.centralwidget)
        self.combo_choose_output.setObjectName("combo_choose_output")
        self.combo_choose_output.addItem("")
        self.combo_choose_output.addItem("")
        self.choose_output.addWidget(self.combo_choose_output)
        self.verticalLayout_2.addLayout(self.choose_output)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.component_1_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.component_1_combobox.setObjectName("component_1_combobox")
        self.component_1_combobox.addItem("")
        self.component_1_combobox.addItem("")
        self.horizontalLayout.addWidget(self.component_1_combobox)
        self.component_1_slider = QtWidgets.QSlider(self.centralwidget)
        self.component_1_slider.setMaximum(100)
        self.component_1_slider.setPageStep(1)
        self.component_1_slider.setProperty("value", 1)
        self.component_1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.component_1_slider.setObjectName("component_1_slider")
        self.horizontalLayout.addWidget(self.component_1_slider)
        self.component_1_slider_lable = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.component_1_slider_lable.setFont(font)
        self.component_1_slider_lable.setObjectName("component_1_slider_lable")
        self.horizontalLayout.addWidget(self.component_1_slider_lable)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.compo_1 = QtWidgets.QHBoxLayout()
        self.compo_1.setObjectName("compo_1")
        self.component_1_check_real = QtWidgets.QCheckBox(self.centralwidget)
        self.component_1_check_real.setObjectName("component_1_check_real")
        self.compo_1.addWidget(self.component_1_check_real)
        self.component_1_check_imag = QtWidgets.QCheckBox(self.centralwidget)
        self.component_1_check_imag.setObjectName("component_1_check_imag")
        self.compo_1.addWidget(self.component_1_check_imag)
        self.component_1_check_mag = QtWidgets.QCheckBox(self.centralwidget)
        self.component_1_check_mag.setObjectName("component_1_check_mag")
        self.compo_1.addWidget(self.component_1_check_mag)
        self.component_1_check_phase = QtWidgets.QCheckBox(self.centralwidget)
        self.component_1_check_phase.setObjectName("component_1_check_phase")
        self.compo_1.addWidget(self.component_1_check_phase)
        self.component_1_check_umag = QtWidgets.QCheckBox(self.centralwidget)
        self.component_1_check_umag.setObjectName("component_1_check_umag")
        self.compo_1.addWidget(self.component_1_check_umag)
        self.component_1_check_uphase = QtWidgets.QCheckBox(self.centralwidget)
        self.component_1_check_uphase.setObjectName("component_1_check_uphase")
        self.compo_1.addWidget(self.component_1_check_uphase)
        self.verticalLayout.addLayout(self.compo_1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.component_2_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.component_2_combobox.setObjectName("component_2_combobox")
        self.component_2_combobox.addItem("")
        self.component_2_combobox.addItem("")
        self.horizontalLayout_6.addWidget(self.component_2_combobox)
        self.component_2_slider = QtWidgets.QSlider(self.centralwidget)
        self.component_2_slider.setMinimum(101)
        self.component_2_slider.setMaximum(201)
        self.component_2_slider.setPageStep(1)
        self.component_2_slider.setProperty("value", 101)
        self.component_2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.component_2_slider.setObjectName("component_2_slider")
        self.horizontalLayout_6.addWidget(self.component_2_slider)
        self.component_2_slider_lable = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.component_2_slider_lable.setFont(font)
        self.component_2_slider_lable.setObjectName("component_2_slider_lable")
        self.horizontalLayout_6.addWidget(self.component_2_slider_lable)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.layout_checkboxes2 = QtWidgets.QHBoxLayout()
        self.layout_checkboxes2.setObjectName("layout_checkboxes2")
        self.component_2_check_real = QtWidgets.QCheckBox(self.centralwidget)
        self.component_2_check_real.setObjectName("component_2_check_real")
        self.layout_checkboxes2.addWidget(self.component_2_check_real)
        self.component_2_check_imag = QtWidgets.QCheckBox(self.centralwidget)
        self.component_2_check_imag.setObjectName("component_2_check_imag")
        self.layout_checkboxes2.addWidget(self.component_2_check_imag)
        self.component_2_check_mag = QtWidgets.QCheckBox(self.centralwidget)
        self.component_2_check_mag.setObjectName("component_2_check_mag")
        self.layout_checkboxes2.addWidget(self.component_2_check_mag)
        self.component_2_check_phase = QtWidgets.QCheckBox(self.centralwidget)
        self.component_2_check_phase.setObjectName("component_2_check_phase")
        self.layout_checkboxes2.addWidget(self.component_2_check_phase)
        self.component_2_check_umag = QtWidgets.QCheckBox(self.centralwidget)
        self.component_2_check_umag.setObjectName("component_2_check_umag")
        self.layout_checkboxes2.addWidget(self.component_2_check_umag)
        self.component_2_check_uphase = QtWidgets.QCheckBox(self.centralwidget)
        self.component_2_check_uphase.setObjectName("component_2_check_uphase")
        self.layout_checkboxes2.addWidget(self.component_2_check_uphase)
        self.verticalLayout_3.addLayout(self.layout_checkboxes2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.output1 = ImageView(self.centralwidget)
        self.output1.setMaximumSize(QtCore.QSize(16777215, 700))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.output1.setFont(font)
        self.output1.setAutoFillBackground(True)
        self.output1.setObjectName("output1")
        self.horizontalLayout_7.addWidget(self.output1)
        self.output2 = ImageView(self.centralwidget)
        self.output2.setMaximumSize(QtCore.QSize(16777215, 700))
        self.output2.setAutoFillBackground(True)
        self.output2.setObjectName("output2")
        self.horizontalLayout_7.addWidget(self.output2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1419, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Open_image = QtWidgets.QAction(MainWindow)
        self.Open_image.setObjectName("Open_image")
        self.Save_image = QtWidgets.QAction(MainWindow)
        self.Save_image.setObjectName("Save_image")
        self.menuFile.addAction(self.Open_image)
        self.menuFile.addAction(self.Save_image)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Block1_label.setText(_translate("MainWindow", "Image 1"))
        self.Block1_combo.setItemText(0, _translate("MainWindow", "Mag"))
        self.Block1_combo.setItemText(1, _translate("MainWindow", "Phase"))
        self.Block1_combo.setItemText(2, _translate("MainWindow", "Real"))
        self.Block1_combo.setItemText(3, _translate("MainWindow", "Imag"))
        self.Block2_label.setText(_translate("MainWindow", "Image 2"))
        self.Block2_combo.setItemText(0, _translate("MainWindow", "Mag"))
        self.Block2_combo.setItemText(1, _translate("MainWindow", "Phase"))
        self.Block2_combo.setItemText(2, _translate("MainWindow", "Real"))
        self.Block2_combo.setItemText(3, _translate("MainWindow", "Imag"))
        self.label.setText(_translate("MainWindow", "Mixer Output to :"))
        self.combo_choose_output.setItemText(0, _translate("MainWindow", "Output1"))
        self.combo_choose_output.setItemText(1, _translate("MainWindow", "Output2"))
        self.label_2.setText(_translate("MainWindow", "Component 1:           "))
        self.component_1_combobox.setItemText(0, _translate("MainWindow", "Image 1"))
        self.component_1_combobox.setItemText(1, _translate("MainWindow", "Image 2"))
        self.component_1_slider_lable.setText(_translate("MainWindow", "0"))
        self.component_1_check_real.setText(_translate("MainWindow", "Real        "))
        self.component_1_check_imag.setText(_translate("MainWindow", "Imag       "))
        self.component_1_check_mag.setText(_translate("MainWindow", "Mag       "))
        self.component_1_check_phase.setText(_translate("MainWindow", "Phase       "))
        self.component_1_check_umag.setText(_translate("MainWindow", "Unit Mag       "))
        self.component_1_check_uphase.setText(_translate("MainWindow", "Unit Phase "))
        self.label_3.setText(_translate("MainWindow", "Component 2:           "))
        self.component_2_combobox.setItemText(0, _translate("MainWindow", "Image 1"))
        self.component_2_combobox.setItemText(1, _translate("MainWindow", "Image 2"))
        self.component_2_slider_lable.setText(_translate("MainWindow", "0"))
        self.component_2_check_real.setText(_translate("MainWindow", "Real       "))
        self.component_2_check_imag.setText(_translate("MainWindow", "Imag       "))
        self.component_2_check_mag.setText(_translate("MainWindow", "Mag       "))
        self.component_2_check_phase.setText(_translate("MainWindow", "Phase       "))
        self.component_2_check_umag.setText(_translate("MainWindow", "Unit Mag     "))
        self.component_2_check_uphase.setText(_translate("MainWindow", "Unit Phase    "))
        self.label_5.setText(_translate("MainWindow", "Output 1"))
        self.label_4.setText(_translate("MainWindow", "Output 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Open_image.setText(_translate("MainWindow", "Open image"))
        self.Open_image.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.Save_image.setText(_translate("MainWindow", "Save image"))
        self.Save_image.setShortcut(_translate("MainWindow", "Ctrl+S"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
